server:
  port: 8081

spring:
  application:
    name: link-rush-api
  datasource:
    url: jdbc:mysql://localhost:3306/link_rush?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  cache:
    type: redis
